### ISSUE TITLE
we can see lot "???" in post_desc_counter.csv 

### ISSUE THREAD

**Issue by rubinliudongpo** [chenjiandongx/51job#1]
Will you please give me a format of this file? currently it is not "UTF-8".

**Comment by chenjiandongx** [comment]
It is `GBK` , you cloud specify encode when you open it with python.

**Comment by rubinliudongpo** [comment]
I  have figured out the root cause, may I push the the updates to your repository?

**Comment by chenjiandongx** [comment]
Sure, 😄

**Comment by rubinliudongpo** [comment]
remote: Permission to chenjiandongx/51job.git denied to rubinliudongpo. :smile:

**Comment by chenjiandongx** [comment]
发个 PR 过来吧
